// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function GetFeedContent() {
  return window['go']['main']['App']['GetFeedContent']();
}

export function GetFeedList() {
  return window['go']['main']['App']['GetFeedList']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function InitDatabase() {
  return window['go']['main']['App']['InitDatabase']();
}

export function SetHistory(arg1) {
  return window['go']['main']['App']['SetHistory'](arg1);
}

export function SetHistoryReaded(arg1) {
  return window['go']['main']['App']['SetHistoryReaded'](arg1);
}
